{% set name = "pdtable" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ca1b03c469f907ab7c1c3a5cc077f0ae558adfb1c6730218a6c02a45053c733

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - pandas

test:
  imports:
    - pdtable

about:
  home: https://github.com/startable/pdtable
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Reads, writes, and manipulates StarTable data.
  description: |
    The pdtable Python package offers interfaces to read, write, and manipulate StarTable data.
    Table blocks are stored as TableDataFrame objects, which inherit from pandas.DataFrame but include additional, hidden metadata. 
    Access to StarTable-specific metadata such as table name, column units etc. is done via the Table proxy. 
  doc_url: https://github.com/startable/pdtable
  dev_url: https://github.com/startable/pdtable

extra:
  recipe-maintainers:
    - jfcorbett
